### ISSUE TITLE
Generic Type Support

### ISSUE THREAD

**Issue by Bryanmuloni** [TaimoorHassan/multiselect#1]
Would you please expand the package to accept generic types like a class object instead of only a String?

**Comment by Ahmadre** [comment]
For all who are searching for somehow generic types:

https://github.com/Ahmadre/multiselect

I also encountered that this package is a little bit buggy and I also tried to fix here and there the implementation.

**Comment by TaimoorHassan** [comment]
multiselect: ^0.0.9 supports generic types
