### ISSUE TITLE
InputDecoration filled=true hides selected options

### ISSUE THREAD

**Issue by SeanPhilippi** [TaimoorHassan/multiselect#5]
If decoration: InputDecoration(filled: true) is used, the options are covered up by the fill color.

**Comment by LPlenk** [comment]
I'm having the same issue. It seems that the problem occurs once you set the fillColor attribute.

**Comment by TaimoorHassan** [comment]
Thanks.  Will fix it today.

**Comment by TaimoorHassan** [comment]
@SeanPhilippi @LPlenk  This is fixed in version 0.1.0. Apologies for the delay
